import { SstStandardDefinition, SstResponsibleProfile, SstBudgetItem, SstBudgetState } from '@/types/sst';

export const initialSstResponsible: SstResponsibleProfile = {
  fullName: 'Ing. Marcela Rincón Ortiz',
  docType: 'CC',
  docNumber: '1.020.784.952',
  professionalRole: 'ESPECIALISTA',
  profession: 'Ingeniera Industrial y Especialista en Seguridad y Salud en el Trabajo',
  licenseNumber: 'LIC-SST-2023-08941',
  licenseExpDate: '2033-05-18',
  course50hDate: '2023-06-10',
  course20hDate: '2026-02-14',
  courseEntity: 'Servicio Nacional de Aprendizaje (SENA) / ARL Sura',
  appointmentDate: '2026-01-15',
  acceptanceDate: '2026-01-16',
  isFormallyAssigned: true,
  hvEvidenceId: 'evi-hv-resp-01',
  licenseEvidenceId: 'evi-lic-resp-01',
  courseEvidenceId: 'evi-curso50-resp-01',
  signedByManager: true,
  signedByResponsible: true,
  managerName: 'Lic. Fernando Ortiz Salazar',
  managerDocNumber: '79.845.120 de Bogotá D.C.'
};

export const initialSstBudgetItems: SstBudgetItem[] = [
  // --- SG-SST (Decreto 1072 de 2015 Art. 2.2.4.6.8 Numeral 4) ---
  {
    id: 'b-sst-01',
    system: 'SST',
    category: 'HUMANO',
    concept: 'Honorarios y Asesoría Técnica Especializada SG-SST',
    description: 'Dirección técnica del SG-SST, higienista industrial y ergonomía de puestos de trabajo.',
    decreto1072Rel: 'Art. 2.2.4.6.8 Numeral 4 y Art. 2.2.4.6.35',
    plannedAmount: 38400000,
    committedAmount: 28800000,
    executedAmount: 9600000,
    quarter: 'ANUAL',
    responsible: 'Gerencia General / Líder SST',
    status: 'EN_EJECUCION'
  },
  {
    id: 'b-sst-02',
    system: 'SST',
    category: 'MEDICO',
    concept: 'Evaluaciones Médicas Ocupacionales de Ingreso, Periódicas y Retiro',
    description: 'Profesiogramas, audiometrías, espirometrías, visiometrías y laboratorios clínicos ocupacionales.',
    decreto1072Rel: 'Art. 2.2.4.6.24 Numeral 1 y Res. 2346/2007',
    plannedAmount: 14500000,
    committedAmount: 11200000,
    executedAmount: 4350000,
    quarter: 'ANUAL',
    responsible: 'Médico Ocupacional / SST',
    status: 'EN_EJECUCION'
  },
  {
    id: 'b-sst-03',
    system: 'SST',
    category: 'EPP',
    concept: 'Dotación de Elementos de Protección Personal (EPP) Certificados',
    description: 'Cascos dieléctricos, botas de seguridad puntera composite, guantes de nitrilo, protección respiratoria.',
    decreto1072Rel: 'Art. 2.2.4.6.24 Numeral 5 y Res. 2400/1979',
    plannedAmount: 22000000,
    committedAmount: 16500000,
    executedAmount: 7800000,
    quarter: 'ANUAL',
    responsible: 'Jefe de Almacén & SST',
    status: 'EN_EJECUCION'
  },
  {
    id: 'b-sst-04',
    system: 'SST',
    category: 'CAPACITACION',
    concept: 'Plan de Capacitación y Entrenamiento en Alturas, Espacios Confinados y Primeros Auxilios',
    description: 'Certificaciones de trabajo seguro en alturas (Res 4272/2021) y brigada integral de emergencias.',
    decreto1072Rel: 'Art. 2.2.4.6.11 Capacitación en SST',
    plannedAmount: 12800000,
    committedAmount: 9400000,
    executedAmount: 3200000,
    quarter: 'ANUAL',
    responsible: 'Líder SST / ARL',
    status: 'EN_EJECUCION'
  },
  {
    id: 'b-sst-05',
    system: 'SST',
    category: 'TECNICO',
    concept: 'Mediciones Ambientales Higiénicas de Ruido (Sonometrías) e Iluminación (Luxometrías)',
    description: 'Estudio de higiene industrial en bodegas de cargue y oficinas según metodología NIOSH.',
    decreto1072Rel: 'Art. 2.2.4.6.15 y Art. 2.2.4.6.24',
    plannedAmount: 8500000,
    committedAmount: 8500000,
    executedAmount: 8500000,
    quarter: 'Q1',
    responsible: 'Líder SST / Laboratorio Higiene',
    status: 'EJECUTADO'
  },
  {
    id: 'b-sst-06',
    system: 'SST',
    category: 'EMERGENCIAS',
    concept: 'Recarga y Mantenimiento de Extintores, Botiquines Tipo B y Simulacro Anual',
    description: 'Recarga de 42 extintores multipropósito, inspección NFPA 10 y dotación de gabinetes contra incendios.',
    decreto1072Rel: 'Art. 2.2.4.6.25 Prevención, Preparación y Respuesta ante Emergencias',
    plannedAmount: 7200000,
    committedAmount: 5100000,
    executedAmount: 1800000,
    quarter: 'ANUAL',
    responsible: 'Comandante de Brigada / SST',
    status: 'EN_EJECUCION'
  },

  // --- INTEGRACIÓN VIAL / PESV (Resolución 40595 de 2022 - Paso 3: Recursos PESV) ---
  {
    id: 'b-pesv-01',
    system: 'PESV',
    category: 'TECNICO',
    concept: 'Mantenimiento Preventivo y Predictivo de Flota Vehicular de Carga',
    description: 'Inspecciones bimestrales, calibración de frenos ABS, alineación y cambio de neumáticos de camiones NPR/FVR.',
    decreto1072Rel: 'Art. 2.2.4.6.24 Numeral 6 (Mantenimiento)',
    pesvRel: 'Res. 40595/2022 - Paso 12: Mantenimiento y Control de Vehículos',
    plannedAmount: 45000000,
    committedAmount: 33750000,
    executedAmount: 14200000,
    quarter: 'ANUAL',
    responsible: 'Jefe de Mantenimiento de Flota',
    status: 'EN_EJECUCION'
  },
  {
    id: 'b-pesv-02',
    system: 'PESV',
    category: 'MEDICO',
    concept: 'Evaluaciones Médicas Ocupacionales con Énfasis Psicosensométrico para Conductores',
    description: 'Exámenes de agudeza visual, campimetría, audiometría tonal y pruebas psicosensométricas especializadas.',
    decreto1072Rel: 'Art. 2.2.4.6.24 Numeral 1 (Salud)',
    pesvRel: 'Res. 40595/2022 - Paso 10: Idoneidad y Evaluación de Conductores',
    plannedAmount: 9800000,
    committedAmount: 7350000,
    executedAmount: 3100000,
    quarter: 'ANUAL',
    responsible: 'Médico Ocupacional / Líder PESV',
    status: 'EN_EJECUCION'
  },
  {
    id: 'b-pesv-03',
    system: 'PESV',
    category: 'CAPACITACION',
    concept: 'Programa de Capacitación Vial: Manejo Defensivo y Prevención del Riesgo en Carretera',
    description: 'Talleres en simulador de conducción, prevención de fatiga/microsueños y normatividad de tránsito Ley 769.',
    decreto1072Rel: 'Art. 2.2.4.6.11 Capacitación',
    pesvRel: 'Res. 40595/2022 - Paso 11: Capacitación en Seguridad Vial',
    plannedAmount: 8200000,
    committedAmount: 6150000,
    executedAmount: 2700000,
    quarter: 'ANUAL',
    responsible: 'Coordinador de Seguridad Vial',
    status: 'EN_EJECUCION'
  },
  {
    id: 'b-pesv-04',
    system: 'PESV',
    category: 'FISICO',
    concept: 'Dotación de Kits de Carretera Reglamentarios, Tacógrafos y Telemática GPS',
    description: 'Equipos de carretera según Art. 30 Código Nacional de Tránsito y monitoreo de velocidad por GPS.',
    decreto1072Rel: 'Art. 2.2.4.6.24 Control de Peligros',
    pesvRel: 'Res. 40595/2022 - Paso 13: Equipos de Seguridad y Telemática',
    plannedAmount: 11500000,
    committedAmount: 9200000,
    executedAmount: 4100000,
    quarter: 'ANUAL',
    responsible: 'Operaciones Logísticas & PESV',
    status: 'EN_EJECUCION'
  }
];

export const initialSstBudgetState: SstBudgetState = {
  fiscalYear: 2026,
  status: 'APROBADO_GERENCIA',
  approvalDate: '2026-01-18 10:30',
  approvedBy: 'Lic. Fernando Ortiz Salazar (Representante Legal)',
  approvalNotes: 'Presupuesto integrado SST + PESV aprobado unánimemente por el Comité Directivo de Gerencia y validado con firmas de las tres partes.',
  financialRoleTitle: 'Director Financiero / Contador Público',
  financialOfficerName: 'Lic. Carlos Mendoza Pardo',
  financialOfficerDoc: '79.654.321 de Bogotá D.C.',
  signatures: {
    manager: {
      name: 'Lic. Fernando Ortiz Salazar',
      title: 'Representante Legal / Gerente General',
      docNumber: '79.845.120 de Bogotá D.C.',
      signedAt: '2026-01-18 10:30',
      token: 'SIG-MGR-892348-SHA256'
    },
    financial: {
      name: 'Lic. Carlos Mendoza Pardo',
      title: 'Director Financiero y Contador Público (T.P. 18452-T)',
      docNumber: '79.654.321 de Bogotá D.C.',
      signedAt: '2026-01-16 16:45',
      token: 'SIG-FIN-472910-SHA256'
    },
    sstLeader: {
      name: 'Ing. Marcela Rincón Ortiz',
      title: 'Líder del SG-SST',
      docNumber: '1.020.784.952 de Bogotá D.C.',
      licenseNumber: 'LIC-SST-2023-08941',
      signedAt: '2026-01-15 14:20',
      token: 'SIG-SST-338291-SHA256'
    }
  },
  copasstReviews: [
    {
      id: 'cop-rev-01',
      meetingDate: '2026-02-18',
      actaNumber: 'Acta Ordinaria No. 02',
      reviewedBy: 'Marcela Rincón (Secretaria COPASST) y Carlos Mendoza (Presidente COPASST)',
      observations: 'El COPASST revisó el avance presupuestal de enero y constató la ejecución de los exámenes médicos de ingreso y dotación de EPP.',
      status: 'CONFORME',
      timestamp: '2026-02-18 17:30'
    },
    {
      id: 'cop-rev-02',
      meetingDate: '2026-03-18',
      actaNumber: 'Acta Ordinaria No. 03',
      reviewedBy: 'Marcela Rincón (Secretaria) y Javier Gómez (Vocal Trabajadores)',
      observations: 'Se revisó la asignación de recursos para el mantenimiento preventivo de la flota PESV y el cronograma de capacitación en alturas. Presupuesto acorde a las necesidades operativas.',
      status: 'CONFORME',
      timestamp: '2026-03-18 16:45'
    }
  ],
  history: [
    {
      id: 'bh-1',
      timestamp: '2026-01-10 14:20',
      role: 'LIDER_SST',
      userName: 'Marcela Rincón Ortiz',
      action: 'Formulación y consolidación del Presupuesto Integrado SST y PESV Vial 2026',
      comment: 'Se integran 6 rubros de SST y 4 rubros obligatorios del PESV según Resolución 40595 de 2022.'
    },
    {
      id: 'bh-2',
      timestamp: '2026-01-14 09:15',
      role: 'DIRECTOR_FINANCIERO',
      userName: 'Carlos Mendoza (Director Financiero / Contador)',
      action: 'Validación de viabilidad económica y asignación de centros de costos',
      comment: 'Asignación aprobada bajo los centros de costos CC-501 (SST) y CC-502 (Flota PESV).'
    },
    {
      id: 'bh-3',
      timestamp: '2026-01-18 10:30',
      role: 'GERENCIA',
      userName: 'Fernando Ortiz (Gerente General)',
      action: 'Aprobación oficial del Presupuesto Anual Integrado con firma digital',
      comment: 'Aprobado formalmente conforme a los requerimientos del Decreto 1072 de 2015 Art. 2.2.4.6.8 Numeral 4.'
    }
  ]
};

export const master60Standards: SstStandardDefinition[] = [
  // ==========================================
  // I. CICLO PLANEAR (25.0%)
  // 1. RECURSOS (10.0%)
  // ==========================================
  {
    id: 'std-1.1.1',
    code: '1.1.1',
    cycle: 'PLANEAR',
    numeralGroup: '1.1 Recursos financieros, técnicos, humanos y de otra índole',
    title: 'Responsable del Sistema de Gestión de Seguridad y Salud en el Trabajo SG-SST',
    criterion: 'Asignar una persona que cumpla con el perfil para diseñar e implementar el SG-SST, con licencia vigente de SST y curso de 50 o 20 horas.',
    decreto1072Article: 'Art. 2.2.4.6.8 Parágrafo 1 y Art. 2.2.4.6.35',
    decreto1072Title: 'Obligaciones de los empleadores - Asignación y perfil del responsable',
    decreto1072Excerpt: 'El empleador debe asignar a una persona que diseñe e implemente el Sistema de Gestión de la Seguridad y Salud en el Trabajo (SG-SST), de acuerdo con la normatividad vigente...',
    weight: 0.5,
    applicableIn7: true,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Solicitar documento formal de asignación, hoja de vida, fotocopia de la licencia en SST y certificación del curso virtual de 50 horas / 20 horas.',
    status: 'CUMPLE',
    evidenceIds: ['evi-hv-resp-01', 'evi-lic-resp-01', 'evi-curso50-resp-01', 'evi-carta-asignacion-01'],
    actionType: 'RESPONSIBLE'
  },
  {
    id: 'std-1.1.2',
    code: '1.1.2',
    cycle: 'PLANEAR',
    numeralGroup: '1.1 Recursos financieros, técnicos, humanos y de otra índole',
    title: 'Responsabilidades en el Sistema de Gestión de Seguridad y Salud en el Trabajo',
    criterion: 'Asignar y comunicar las responsabilidades específicas en SST a todos los niveles de la organización.',
    decreto1072Article: 'Art. 2.2.4.6.8 Numeral 2',
    decreto1072Title: 'Obligaciones de los empleadores - Asignación y comunicación de responsabilidades',
    decreto1072Excerpt: 'Asignar, documentar y comunicar las responsabilidades específicas en Seguridad y Salud en el Trabajo (SST) a todos los niveles de la organización, incluida la alta dirección...',
    weight: 0.5,
    applicableIn7: true,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Verificar documento que contenga la asignación de responsabilidades en SST a cada uno de los niveles y las constancias de su comunicación.',
    status: 'CUMPLE',
    evidenceIds: ['evi-carta-asignacion-01'],
    actionType: 'RESPONSIBLE'
  },
  {
    id: 'std-1.1.3',
    code: '1.1.3',
    cycle: 'PLANEAR',
    numeralGroup: '1.1 Recursos financieros, técnicos, humanos y de otra índole',
    title: 'Asignación de Recursos para el SG-SST (Financieros, Técnicos, Físicos y Personal)',
    criterion: 'Definir y asignar los recursos financieros, técnicos, humanos y físicos necesarios para el diseño, implementación, revisión y mejora del SG-SST.',
    decreto1072Article: 'Art. 2.2.4.6.8 Numeral 4',
    decreto1072Title: 'Obligaciones de los empleadores - Definición de recursos',
    decreto1072Excerpt: 'Definir y asignar los recursos financieros, técnicos y el personal necesario para el diseño, implementación, revisión, evaluación y mejora de las medidas de prevención y control...',
    weight: 0.5,
    applicableIn7: true,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar presupuesto asignado para SST con firma de la Gerencia, soportes de ejecución y balances de gastos periódicos.',
    status: 'CUMPLE',
    evidenceIds: ['evi-presupuesto-2026'],
    actionType: 'BUDGET'
  },
  {
    id: 'std-1.1.4',
    code: '1.1.4',
    cycle: 'PLANEAR',
    numeralGroup: '1.1 Recursos financieros, técnicos, humanos y de otra índole',
    title: 'Afiliación al Sistema General de Riesgos Laborales',
    criterion: 'Garantizar que todos los trabajadores independientes, dependientes y contratistas estén afiliados al Sistema General de Riesgos Laborales según su clase de riesgo.',
    decreto1072Article: 'Art. 2.2.4.6.8 Numeral 1',
    decreto1072Title: 'Obligaciones de los empleadores - Afiliación al Sistema General de Riesgos Laborales',
    decreto1072Excerpt: 'Definir, firmar y divulgar la política de SST y garantizar la afiliación de los trabajadores al Sistema General de Riesgos Laborales...',
    weight: 0.5,
    applicableIn7: true,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar planillas integradas de liquidación de aportes (PILA) de los últimos meses de todo el personal.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-1.1.5',
    code: '1.1.5',
    cycle: 'PLANEAR',
    numeralGroup: '1.1 Recursos financieros, técnicos, humanos y de otra índole',
    title: 'Pago de Pensión Especial para Trabajadores en Actividades de Alto Riesgo',
    criterion: 'Identificar a los trabajadores que se dediquen de forma permanente a actividades de alto riesgo y realizar la cotización especial a pensiones.',
    decreto1072Article: 'Art. 2.2.4.6.8 y Decreto 2090 de 2003',
    decreto1072Title: 'Pensiones especiales para actividades de alto riesgo',
    decreto1072Excerpt: 'El empleador debe identificar las actividades de alto riesgo descritas en el Decreto 2090 de 2003 y cotizar los puntos adicionales correspondientes a la pensión especial.',
    weight: 0.5,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Constatar la lista de cargos con cotización especial en la planilla PILA o certificar la no realización de dichas labores.',
    status: 'NO_APLICA_JUSTIFICADO',
    evidenceIds: [],
    actionType: 'GENERAL',
    notes: 'La empresa certifica que no realiza actividades clasificadas como alto riesgo en pensiones conforme al Decreto 2090/2003.'
  },
  {
    id: 'std-1.1.6',
    code: '1.1.6',
    cycle: 'PLANEAR',
    numeralGroup: '1.1 Recursos financieros, técnicos, humanos y de otra índole',
    title: 'Conformación y Funcionamiento del COPASST o Vigía de Seguridad y Salud en el Trabajo',
    criterion: 'Conformar el COPASST (más de 10 trabajadores) o nombrar el Vigía de SST (menos de 10 trabajadores), con actas de elección y reuniones mensuales.',
    decreto1072Article: 'Art. 2.2.4.6.8 Numeral 9 y Art. 2.2.4.6.9',
    decreto1072Title: 'Participación de los trabajadores y conformación del COPASST',
    decreto1072Excerpt: 'Asegurar la adopción de medidas eficaces que garanticen la participación de todos los trabajadores y sus representantes ante el Comité Paritario o Vigía...',
    weight: 0.5,
    applicableIn7: true,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Solicitar acta de conformación del COPASST o Vigía de SST, registro de votaciones y actas de reuniones mensuales.',
    status: 'CUMPLE',
    evidenceIds: ['acta-copasst-2025-2027'],
    actionType: 'COPASST'
  },
  {
    id: 'std-1.1.7',
    code: '1.1.7',
    cycle: 'PLANEAR',
    numeralGroup: '1.1 Recursos financieros, técnicos, humanos y de otra índole',
    title: 'Capacitación de los Integrantes del COPASST o Vigía de SST',
    criterion: 'Capacitar a los integrantes del COPASST o al Vigía de SST en sus funciones legales y temas de seguridad y salud en el trabajo.',
    decreto1072Article: 'Art. 2.2.4.6.11',
    decreto1072Title: 'Capacitación en Seguridad y Salud en el Trabajo',
    decreto1072Excerpt: 'El empleador o contratante debe desarrollar un programa de capacitación que proporcione conocimiento para identificar los peligros y controlar los riesgos...',
    weight: 0.5,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar certificados de capacitación o asistencia de los miembros del COPASST en investigación de AT, inspecciones y rol paritario.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'COPASST'
  },
  {
    id: 'std-1.1.8',
    code: '1.1.8',
    cycle: 'PLANEAR',
    numeralGroup: '1.1 Recursos financieros, técnicos, humanos y de otra índole',
    title: 'Conformación y Funcionamiento del Comité de Convivencia Laboral',
    criterion: 'Conformar el Comité de Convivencia Laboral, con periodo de dos años, reuniones mensuales ordinarias y trámite confidencial de quejas.',
    decreto1072Article: 'Resolución 3461 de 2025, Ley 1010 de 2006 y Ley 2365 de 2024',
    decreto1072Title: 'Prevención del acoso laboral, violencia en el trabajo y funcionamiento del CCL',
    decreto1072Excerpt: 'Conformación paritaria y funcionamiento del Comité de Convivencia Laboral, con sesiones ordinarias mensuales obligatorias, protocolo de quejas y medidas preventivas.',
    weight: 0.5,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Solicitar acta de conformación paritaria, actas de reuniones mensuales (12 ordinarias al año) e informes de gestión del CCL conforme a la Resolución 3461 de 2025.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'CCL'
  },
  {
    id: 'std-1.2.1',
    code: '1.2.1',
    cycle: 'PLANEAR',
    numeralGroup: '1.2 Capacitación en el SG-SST',
    title: 'Programa de Capacitación Anual en Seguridad y Salud en el Trabajo',
    criterion: 'Elaborar y ejecutar el programa de capacitación anual en SST enfocado en los peligros prioritarios y evaluado periódicamente.',
    decreto1072Article: 'Art. 2.2.4.6.11',
    decreto1072Title: 'Capacitación en Seguridad y Salud en el Trabajo',
    decreto1072Excerpt: 'El programa de capacitación en seguridad y salud en el trabajo - SST, debe ser revisado mínimo una (1) vez al año, con la participación del Comité Paritario o Vigía...',
    weight: 2.0,
    applicableIn7: true,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Solicitar el programa de capacitación anual en SST, cronograma y registros de asistencia con evaluaciones de eficacia.',
    status: 'EN_PROCESO',
    evidenceIds: [],
    actionType: 'TRAINING'
  },
  {
    id: 'std-1.2.2',
    code: '1.2.2',
    cycle: 'PLANEAR',
    numeralGroup: '1.2 Capacitación en el SG-SST',
    title: 'Capacitación, Inducción y Reinducción en SST para Todo el Personal',
    criterion: 'Realizar actividades de inducción y reinducción en SST a todos los trabajadores independientemente de su forma de contratación.',
    decreto1072Article: 'Art. 2.2.4.6.11 Parágrafo 2',
    decreto1072Title: 'Inducción y reinducción obligatoria',
    decreto1072Excerpt: 'El empleador proporcionará a todo trabajador que ingrese por primera vez a la empresa, independiente de su forma de contratación y vinculación, una inducción en los aspectos generales y específicos...',
    weight: 2.0,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar registros firmados de inducción y reinducción en SST de trabajadores nuevos y antiguos.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'TRAINING'
  },
  {
    id: 'std-1.2.3',
    code: '1.2.3',
    cycle: 'PLANEAR',
    numeralGroup: '1.2 Capacitación en el SG-SST',
    title: 'Responsables del SG-SST con Curso Virtual de 50 Horas / 20 Horas',
    criterion: 'El responsable del SG-SST y los miembros del COPASST deben contar con la certificación del curso virtual de 50 horas de SST y sus actualizaciones de 20 horas.',
    decreto1072Article: 'Art. 2.2.4.6.35 y Res. 4927 de 2016',
    decreto1072Title: 'Capacitación obligatoria de 50 horas en SST',
    decreto1072Excerpt: 'Los responsables de la ejecución de los Sistemas de Gestión de la Seguridad y Salud en el Trabajo (SG-SST), deberán realizar el curso de capacitación virtual de cincuenta (50) horas...',
    weight: 2.0,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Verificar certificados del curso virtual de 50 horas de SST y de actualización de 20 horas según corresponda.',
    status: 'CUMPLE',
    evidenceIds: ['evi-curso50-resp-01'],
    actionType: 'RESPONSIBLE'
  },

  // 2. GESTIÓN INTEGRAL DEL SG-SST (15.0%)
  {
    id: 'std-2.1.1',
    code: '2.1.1',
    cycle: 'PLANEAR',
    numeralGroup: '2.1 Política y Objetivos de SST',
    title: 'Política de Seguridad y Salud en el Trabajo Documentada, Firmada y Divulgada',
    criterion: 'Definir por escrito la Política de SST con fecha, firmada por el representante legal, difundida al COPASST y a todos los trabajadores.',
    decreto1072Article: 'Art. 2.2.4.6.5, Art. 2.2.4.6.6 y Art. 2.2.4.6.7',
    decreto1072Title: 'Política de Seguridad y Salud en el Trabajo',
    decreto1072Excerpt: 'El empleador o contratante debe establecer por escrito una política de Seguridad y Salud en el Trabajo (SST) que debe ser parte de las políticas de gestión de la empresa...',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar la política escrita, fechada, firmada por el representante legal vigente y constancia de su socialización.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'POLICY'
  },
  {
    id: 'std-2.1.2',
    code: '2.1.2',
    cycle: 'PLANEAR',
    numeralGroup: '2.1 Política y Objetivos de SST',
    title: 'Objetivos de SST Definidos, Medibles y Cuantificables',
    criterion: 'Definir objetivos de SST claros, medibles, cuantificables y coherentes con la política y las prioridades de riesgos.',
    decreto1072Article: 'Art. 2.2.4.6.17 y Art. 2.2.4.6.18',
    decreto1072Title: 'Objetivos del Sistema de Gestión de la Seguridad y Salud en el Trabajo',
    decreto1072Excerpt: 'Los objetivos deben ser medibles, específicos para la empresa, alineados con la política de SST y revisados anualmente.',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Verificar documento con los objetivos de SST formulados y sus metas e indicadores asociados.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'POLICY'
  },
  {
    id: 'std-2.1.3',
    code: '2.1.3',
    cycle: 'PLANEAR',
    numeralGroup: '2.1 Política y Objetivos de SST',
    title: 'Evaluación Inicial del SG-SST Realizada',
    criterion: 'Realizar la evaluación inicial del SG-SST con el fin de identificar prioridades y formular el plan de trabajo anual.',
    decreto1072Article: 'Art. 2.2.4.6.16',
    decreto1072Title: 'Evaluación inicial del Sistema de Gestión de la Seguridad y Salud en el Trabajo',
    decreto1072Excerpt: 'La evaluación inicial debe incluir la identificación de la normatividad vigente, verificación de los peligros y evaluación de la eficacia de las medidas previas.',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar la evaluación inicial documentada con corte a diciembre y plan de mejoramiento derivado.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-2.1.4',
    code: '2.1.4',
    cycle: 'PLANEAR',
    numeralGroup: '2.1 Política y Objetivos de SST',
    title: 'Plan Anual de Trabajo Firmado con Cronograma y Recursos Asignados',
    criterion: 'Diseñar y firmar el Plan Anual de Trabajo de SST, el cual debe contemplar metas, responsabilidades, recursos y cronograma.',
    decreto1072Article: 'Art. 2.2.4.6.8 Numeral 7',
    decreto1072Title: 'Plan de Trabajo Anual en SST',
    decreto1072Excerpt: 'Diseñar y desarrollar un plan de trabajo anual para alcanzar cada uno de los objetivos propuestos en el SG-SST, el cual debe identificar claramente metas, responsabilidades, recursos y cronograma...',
    weight: 2.0,
    applicableIn7: true,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar el plan de trabajo anual firmado por el empleador y el responsable de SST, junto con los avances de su ejecución.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-2.2.1',
    code: '2.2.1',
    cycle: 'PLANEAR',
    numeralGroup: '2.2 Archivo y Retención Documental',
    title: 'Archivo y Retención Documental del SG-SST Garantizada por 20 Años',
    criterion: 'Contar con un sistema de archivo y retención documental que conserve los registros de SST por mínimo 20 años desde el cese del trabajador.',
    decreto1072Article: 'Art. 2.2.4.6.12 y Art. 2.2.4.6.13',
    decreto1072Title: 'Documentación y Conservación de los documentos',
    decreto1072Excerpt: 'El empleador debe conservar los registros y documentos que soportan el SG-SST de manera controlada, garantizando que sean legibles, identificables y protegidos contra daño por mínimo veinte (20) años...',
    weight: 2.0,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Constatar el procedimiento de archivo físico o digital con copias de seguridad y tiempos de retención definidos.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-2.3.1',
    code: '2.3.1',
    cycle: 'PLANEAR',
    numeralGroup: '2.3 Rendición de Cuentas',
    title: 'Rendición de Cuentas sobre el Desempeño en SST',
    criterion: 'Realizar anualmente la rendición de cuentas del desempeño en SST a todos los niveles que tengan responsabilidades asignadas.',
    decreto1072Article: 'Art. 2.2.4.6.8 Numeral 3',
    decreto1072Title: 'Rendición de cuentas al interior de la empresa',
    decreto1072Excerpt: 'A quienes se les hayan asignado responsabilidades en el Sistema de Gestión de la Seguridad y Salud en el Trabajo (SG-SST), tienen la obligación de rendir cuentas internamente sobre su desempeño...',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar registros de rendición de cuentas anual elaborada por la alta dirección y los responsables de procesos.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-2.4.1',
    code: '2.4.1',
    cycle: 'PLANEAR',
    numeralGroup: '2.4 Matriz Legal',
    title: 'Matriz de Requisitos Legales Actualizada',
    criterion: 'Mantener actualizada la matriz de requisitos legales aplicables en SST conforme a la normatividad colombiana vigente.',
    decreto1072Article: 'Art. 2.2.4.6.8 Numeral 2 y Art. 2.2.4.6.12 Numeral 15',
    decreto1072Title: 'Cumplimiento de los requisitos normativos aplicables',
    decreto1072Excerpt: 'Garantizar que opera bajo el cumplimiento de la normatividad nacional vigente aplicable en materia de seguridad y salud en el trabajo...',
    weight: 2.0,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar la matriz legal en SST con evidencia de evaluación de cumplimiento periódica.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-2.5.1',
    code: '2.5.1',
    cycle: 'PLANEAR',
    numeralGroup: '2.5 Comunicación',
    title: 'Mecanismos de Comunicación Interna y Externa en SST',
    criterion: 'Disponer de mecanismos eficaces de comunicación interna y externa relativos a la seguridad y salud en el trabajo.',
    decreto1072Article: 'Art. 2.2.4.6.14',
    decreto1072Title: 'Comunicación en el SG-SST',
    decreto1072Excerpt: 'El empleador debe establecer mecanismos eficaces para recibir, documentar y responder adecuadamente a las comunicaciones internas y externas relativas a la SST...',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar procedimiento y canales de comunicación (buzones, carteleras, intranet) con registros de respuestas a inquietudes.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-2.6.1',
    code: '2.6.1',
    cycle: 'PLANEAR',
    numeralGroup: '2.6 Adquisiciones',
    title: 'Identificación y Evaluación en Adquisiciones de Bienes y Servicios',
    criterion: 'Establecer y mantener un procedimiento para evaluar el impacto en SST en las compras y adquisiciones de productos, insumos y equipos.',
    decreto1072Article: 'Art. 2.2.4.6.27',
    decreto1072Title: 'Adquisiciones',
    decreto1072Excerpt: 'El empleador debe establecer y mantener un procedimiento con el fin de garantizar que se identifiquen y evalúen en las adquisiciones de bienes y servicios las especificaciones relativas a SST...',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Verificar procedimiento de compras que contemple criterios de SST y fichas de seguridad en compras de productos.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-2.7.1',
    code: '2.7.1',
    cycle: 'PLANEAR',
    numeralGroup: '2.7 Contratación y Proveedores',
    title: 'Evaluación y Selección de Proveedores y Contratistas en SST',
    criterion: 'Adoptar disposiciones para que se cumplan las normas de SST por parte de proveedores, trabajadores en misión y contratistas.',
    decreto1072Article: 'Art. 2.2.4.6.28',
    decreto1072Title: 'Contratación en SST',
    decreto1072Excerpt: 'El empleador debe adoptar y mantener las disposiciones que garanticen el cumplimiento de las normas de seguridad y salud en el trabajo de su empresa por parte de los proveedores y contratistas...',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar manual de contratistas, cartas de inducción, verificación de seguridad social antes de ingreso y auditorías a proveedores.',
    status: 'EN_PROCESO',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-2.8.1',
    code: '2.8.1',
    cycle: 'PLANEAR',
    numeralGroup: '2.8 Gestión del Cambio',
    title: 'Procedimiento para la Gestión del Cambio',
    criterion: 'Implementar un procedimiento para evaluar el impacto sobre la SST de los cambios internos (procesos, instalaciones) y externos (normas).',
    decreto1072Article: 'Art. 2.2.4.6.26',
    decreto1072Title: 'Gestión del cambio',
    decreto1072Excerpt: 'El empleador o contratante debe implementar y mantener un procedimiento para evaluar el impacto sobre la seguridad y salud en el trabajo que puedan generar los cambios internos o externos...',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Solicitar procedimiento de gestión del cambio y formatos aplicados en modificaciones locativas o de maquinaria.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-2.9.1',
    code: '2.9.1',
    cycle: 'PLANEAR',
    numeralGroup: '2.9 Información',
    title: 'Custodia y Entrega de Información a los Trabajadores',
    criterion: 'Garantizar el acceso de los trabajadores a la información sobre los riesgos de su labor y las medidas de prevención implementadas.',
    decreto1072Article: 'Art. 2.2.4.6.12',
    decreto1072Title: 'Acceso a la información documental del SG-SST',
    decreto1072Excerpt: 'Los documentos deben estar bajo custodia del responsable del SG-SST y garantizar el acceso a los trabajadores y sus representantes.',
    weight: 0.5,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar mecanismos físicos y digitales donde los trabajadores consultan el SG-SST.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-2.10.1',
    code: '2.10.1',
    cycle: 'PLANEAR',
    numeralGroup: '2.10 Procedimientos e Instructivos',
    title: 'Procedimientos e Instructivos Internos de Seguridad y Salud en el Trabajo',
    criterion: 'Elaborar y difundir procedimientos e instructivos de trabajo seguro para las actividades rutinarias y no rutinarias.',
    decreto1072Article: 'Art. 2.2.4.6.12 Numeral 6 y Art. 2.2.4.6.24',
    decreto1072Title: 'Procedimientos e instructivos internos de SST',
    decreto1072Excerpt: 'Los procedimientos de trabajo seguro y las fichas técnicas deben estar disponibles y ser divulgados a todos los trabajadores...',
    weight: 0.5,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar manual de procedimientos operativos estandarizados (POE) de seguridad con registro de socialización.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },

  // ==========================================
  // II. CICLO HACER (60.0%)
  // 3. GESTIÓN DE LA SALUD (20.0%)
  // ==========================================
  {
    id: 'std-3.1.1',
    code: '3.1.1',
    cycle: 'HACER',
    numeralGroup: '3.1 Condiciones de Salud en el Trabajo',
    title: 'Diagnóstico de Condiciones de Salud de los Trabajadores',
    criterion: 'Elaborar el diagnóstico de condiciones de salud de la población trabajadora con base en los exámenes médicos ocupacionales periódicos.',
    decreto1072Article: 'Art. 2.2.4.6.24 Numeral 1 y Res. 2346 de 2007',
    decreto1072Title: 'Gestión de la salud - Diagnóstico epidemiológico',
    decreto1072Excerpt: 'El empleador debe realizar las evaluaciones médicas ocupacionales y elaborar el diagnóstico de las condiciones de salud de sus trabajadores...',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Solicitar informe consolidado de condiciones de salud anual emitido por la IPS médica con perfil sociodemográfico.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-3.1.2',
    code: '3.1.2',
    cycle: 'HACER',
    numeralGroup: '3.1 Condiciones de Salud en el Trabajo',
    title: 'Evaluaciones Médicas Ocupacionales de Ingreso, Periódicas y Retiro',
    criterion: 'Realizar las evaluaciones médicas ocupacionales conforme al profesiograma y la Resolución 2346 de 2007.',
    decreto1072Article: 'Art. 2.2.4.6.24 Numeral 1 y Res. 2346 de 2007',
    decreto1072Title: 'Evaluaciones médicas ocupacionales reglamentarias',
    decreto1072Excerpt: 'Realizar evaluaciones médicas ocupacionales de acuerdo con los peligros a los que está expuesto el trabajador y el perfil del cargo...',
    weight: 2.0,
    applicableIn7: true,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar profesiograma y certificados de aptitud médica ocupacional emitidos por médico con licencia en SST.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-3.1.3',
    code: '3.1.3',
    cycle: 'HACER',
    numeralGroup: '3.1 Condiciones de Salud en el Trabajo',
    title: 'Información Oportuna al Médico Evaluador sobre Perfiles de Cargo',
    criterion: 'Suministrar al médico ocupacional la descripción sociodemográfica, perfiles del cargo, matriz de peligros y profesiograma.',
    decreto1072Article: 'Art. 2.2.4.6.24',
    decreto1072Title: 'Suministro de información al médico de salud ocupacional',
    decreto1072Excerpt: 'El empleador debe informar a los médicos que realizan las evaluaciones médicas ocupacionales las condiciones de trabajo y los peligros...',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar constancia de remisión del profesiograma y matriz de peligros al médico evaluador de la IPS.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-3.1.4',
    code: '3.1.4',
    cycle: 'HACER',
    numeralGroup: '3.1 Condiciones de Salud en el Trabajo',
    title: 'Exámenes Paraclínicos con Énfasis Específico según el Riesgo',
    criterion: 'Realizar los exámenes paraclínicos (audiometría, espirometría, visiometría, osteomuscular) de acuerdo con los factores de riesgo prioritarios.',
    decreto1072Article: 'Res. 2346 de 2007',
    decreto1072Title: 'Pruebas complementarias y paraclínicos ocupacionales',
    decreto1072Excerpt: 'Las valoraciones paraclínicas deben corresponder estrictamente a los riesgos a los cuales se expone el colaborador en su labor.',
    weight: 2.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Verificar conceptos de aptitud médica donde se evidencia la realización de paraclínicos acordes a los riesgos.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-3.1.5',
    code: '3.1.5',
    cycle: 'HACER',
    numeralGroup: '3.1 Condiciones de Salud en el Trabajo',
    title: 'Custodia de Historias Clínicas Ocupacionales por Médico Especialista',
    criterion: 'Garantizar que las historias clínicas ocupacionales permanezcan en custodia exclusiva de la IPS médica autorizada o del médico de la empresa.',
    decreto1072Article: 'Res. 2346 de 2007 Art. 16 y Res. 1918 de 2009',
    decreto1072Title: 'Reserva legal de la historia clínica ocupacional',
    decreto1072Excerpt: 'Las historias clínicas ocupacionales son documentos privados sometidos a reserva legal que reposarán exclusivamente en la IPS de salud ocupacional...',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Solicitar carta de custodia de historias clínicas suscrita por la IPS médica y verificar que en la empresa solo reposen certificados de aptitud.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-3.1.6',
    code: '3.1.6',
    cycle: 'HACER',
    numeralGroup: '3.1 Condiciones de Salud en el Trabajo',
    title: 'Restricciones y Recomendaciones Médico-Laborales Comunicadas y Acatadas',
    criterion: 'Comunicar oportunamente y dar cumplimiento estricto a las restricciones y recomendaciones emanadas de EPS, ARL o IPS médica.',
    decreto1072Article: 'Art. 2.2.4.6.24',
    decreto1072Title: 'Cumplimiento de recomendaciones médico laborales',
    decreto1072Excerpt: 'El empleador debe realizar las adecuaciones de puestos de trabajo y reubicaciones necesarias frente a recomendaciones emitidas...',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar matriz de seguimiento a casos médicos con constancia de entrega de recomendaciones al jefe inmediato y al trabajador.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-3.1.7',
    code: '3.1.7',
    cycle: 'HACER',
    numeralGroup: '3.1 Condiciones de Salud en el Trabajo',
    title: 'Programas de Promoción de Estilos de Vida y Entornos Saludables',
    criterion: 'Desarrollar actividades de promoción y prevención de la salud orientadas a la adopción de estilos de vida saludables (cardiovascular, pausas activas, antitabaco).',
    decreto1072Article: 'Art. 2.2.4.6.11 y Ley 1335 de 2009',
    decreto1072Title: 'Promoción y prevención de la salud en el trabajo',
    decreto1072Excerpt: 'Fomentar la adopción de estilos de vida saludable en el trabajo y prevenir el consumo de sustancias psicoactivas y tabaco...',
    weight: 2.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar registros de jornadas de salud, pausas activas, talleres de nutrición y campañas de prevención de tabaquismo.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-3.1.8',
    code: '3.1.8',
    cycle: 'HACER',
    numeralGroup: '3.1 Condiciones de Salud en el Trabajo',
    title: 'Servicios de Higiene, Agua Potable y Manejo de Aguas Residuales',
    criterion: 'Garantizar el suministro de agua potable, servicios sanitarios higiénicos diferenciados por sexo y manejo de aguas servidas.',
    decreto1072Article: 'Res. 2400 de 1979 Título II',
    decreto1072Title: 'Servicios de higiene y saneamiento básico industrial',
    decreto1072Excerpt: 'En todo establecimiento de trabajo se proveerá de agua potable adecuada y servicios sanitarios higiénicos...',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Verificar análisis microbiológico y fisicoquímico de agua potable y condiciones de higiene de las baterías sanitarias.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-3.1.9',
    code: '3.1.9',
    cycle: 'HACER',
    numeralGroup: '3.1 Condiciones de Salud en el Trabajo',
    title: 'Manejo Integral de Residuos Ordinarios y Peligrosos RESPEL',
    criterion: 'Eliminar y disponer adecuadamente los residuos sólidos ordinarios y peligrosos generados en la operación con gestores autorizados.',
    decreto1072Article: 'Decreto 1076 de 2015 y Dec. 1072 de 2015',
    decreto1072Title: 'Manejo integral de residuos y saneamiento',
    decreto1072Excerpt: 'Garantizar la adecuada gestión ambiental y sanitaria de residuos peligrosos generados en la actividad productiva.',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar certificados de disposición final de residuos peligrosos (RESPEL) y registro en PGIRS.',
    status: 'CUMPLE',
    evidenceIds: ['evi-002'],
    actionType: 'GENERAL'
  },
  {
    id: 'std-3.2.1',
    code: '3.2.1',
    cycle: 'HACER',
    numeralGroup: '3.2 Registro, Reporte e Investigación de ATEL',
    title: 'Reporte de Accidentes de Trabajo y Enfermedades Laborales (ATEL) a ARL y EPS',
    criterion: 'Reportar oportunamente a la ARL y EPS todos los accidentes de trabajo y diagnósticos de enfermedades laborales dentro de los dos (2) días hábiles siguientes.',
    decreto1072Article: 'Art. 2.2.4.6.32 y Res. 156 de 2005',
    decreto1072Title: 'Reporte de accidentes de trabajo y enfermedades laborales',
    decreto1072Excerpt: 'El empleador o contratante está obligado a reportar a la Administradora de Riesgos Laborales (ARL) y a la Entidad Promotora de Salud (EPS) todos los accidentes de trabajo y las enfermedades laborales diagnosticadas dentro de los dos (2) días hábiles...',
    weight: 2.0,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar los FURAT y FUREL radicados dentro de los dos días hábiles posteriores al evento.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-3.2.2',
    code: '3.2.2',
    cycle: 'HACER',
    numeralGroup: '3.2 Registro, Reporte e Investigación de ATEL',
    title: 'Investigación de Incidentes, Accidentes y Enfermedades con el COPASST',
    criterion: 'Investigar todos los incidentes y accidentes de trabajo con participación del COPASST, profesional en SST y jefe inmediato dentro de los 15 días.',
    decreto1072Article: 'Res. 1401 de 2007 y Art. 2.2.4.6.32',
    decreto1072Title: 'Investigación de incidentes y accidentes de trabajo',
    decreto1072Excerpt: 'El equipo investigador debe identificar las causas básicas e inmediatas y generar un plan de acción correctivo remitido a la ARL para eventos graves...',
    weight: 2.0,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar informes de investigación en formato Resolución 1401 de 2007 con análisis de causas tipo Espina de Pescado / Árbol de causas y firmas del COPASST.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'COPASST'
  },
  {
    id: 'std-3.2.3',
    code: '3.2.3',
    cycle: 'HACER',
    numeralGroup: '3.2 Registro, Reporte e Investigación de ATEL',
    title: 'Registro Estadístico de Accidentes de Trabajo y Enfermedades Laborales',
    criterion: 'Llevar el registro estadístico mensual de accidentes de trabajo, enfermedades laborales e incidentes, consolidado anualmente.',
    decreto1072Article: 'Art. 2.2.4.6.20, Art. 2.2.4.6.21 y Art. 2.2.4.6.22',
    decreto1072Title: 'Registro y seguimiento estadístico de ATEL',
    decreto1072Excerpt: 'Consolidar mensualmente las estadísticas de accidentalidad y enfermedad laboral para retroalimentar la matriz de peligros...',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar matriz consolidada de eventos con causas, días de incapacidad y partes del cuerpo afectadas.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-3.3.1',
    code: '3.3.1',
    cycle: 'HACER',
    numeralGroup: '3.3 Mecanismos de Vigilancia Epidemiológica',
    title: 'Medición de Severidad, Frecuencia y Mortalidad de los Accidentes Laborales',
    criterion: 'Calcular mensualmente los indicadores mínimos: Índice de Frecuencia de AT (IF), Índice de Severidad de AT (IS), Proporción de AT mortales y Letalidad.',
    decreto1072Article: 'Art. 2.2.4.6.22 y Res. 0312 Art. 30',
    decreto1072Title: 'Indicadores mínimos de accidentalidad',
    decreto1072Excerpt: 'Medir trimestral y anualmente la frecuencia, severidad y tasa de accidentalidad laboral de acuerdo con las fórmulas reglamentarias...',
    weight: 2.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Verificar fichas técnicas de los indicadores con fórmulas del Artículo 30 de la Resolución 0312 de 2019.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-3.3.2',
    code: '3.3.2',
    cycle: 'HACER',
    numeralGroup: '3.3 Mecanismos de Vigilancia Epidemiológica',
    title: 'Medición y Registro del Ausentismo Laboral por Causa Médica',
    criterion: 'Medir el ausentismo laboral clasificándolo por causa médica (enfermedad común, accidente de trabajo, enfermedad laboral).',
    decreto1072Article: 'Art. 2.2.4.6.22',
    decreto1072Title: 'Indicadores de resultado - Ausentismo laboral',
    decreto1072Excerpt: 'Medición periódica del ausentismo laboral derivado de contingencias de salud común y laboral...',
    weight: 1.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar registros mensuales de ausentismo con cálculo del índice de frecuencia y severidad del ausentismo.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },

  // 4. GESTIÓN DE PELIGROS Y RIESGOS (30.0%)
  {
    id: 'std-4.1.1',
    code: '4.1.1',
    cycle: 'HACER',
    numeralGroup: '4.1 Identificación de Peligros y Valoración de Riesgos',
    title: 'Metodología para Identificación de Peligros, Evaluación y Valoración de Riesgos (GTC 45)',
    criterion: 'Definir y aplicar una metodología sistemática para identificar peligros, evaluar y valorar los riesgos (GTC 45) en todos los procesos.',
    decreto1072Article: 'Art. 2.2.4.6.15',
    decreto1072Title: 'Identificación de peligros, evaluación y valoración de los riesgos',
    decreto1072Excerpt: 'El empleador o contratante debe aplicar una metodología sistemática, que tenga alcance sobre todos los procesos y actividades rutinarias y no rutinarias internas o externas...',
    weight: 4.0,
    applicableIn7: true,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar matriz IPEVR bajo GTC 45 que cubra la totalidad de sedes, centros de trabajo y cargos.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'HAZARDS'
  },
  {
    id: 'std-4.1.2',
    code: '4.1.2',
    cycle: 'HACER',
    numeralGroup: '4.1 Identificación de Peligros y Valoración de Riesgos',
    title: 'Identificación de Peligros con Participación de Todos los Niveles',
    criterion: 'Garantizar la participación de los trabajadores en la identificación de peligros y actualizar la matriz ante cualquier accidente grave o cambio.',
    decreto1072Article: 'Art. 2.2.4.6.15 Parágrafo 1',
    decreto1072Title: 'Participación en la identificación de peligros',
    decreto1072Excerpt: 'Se debe contar con la participación y consulta de todos los trabajadores en la identificación de los peligros y valoración de los riesgos...',
    weight: 4.0,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Verificar actas o formatos de reporte de actos/condiciones inseguras diligenciados por trabajadores operativos.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'HAZARDS'
  },
  {
    id: 'std-4.1.3',
    code: '4.1.3',
    cycle: 'HACER',
    numeralGroup: '4.1 Identificación de Peligros y Valoración de Riesgos',
    title: 'Identificación de Sustancias Químicas Cancerígenas o de Alta Toxicidad',
    criterion: 'Identificar sustancias químicas catalogadas como cancerígenas o con toxicidad aguda, priorizando medidas preventivas y fichas FDS.',
    decreto1072Article: 'Art. 2.2.4.6.15 y Dec. 1496 de 2018 (SGA)',
    decreto1072Title: 'Gestión del riesgo químico y sustancias cancerígenas',
    decreto1072Excerpt: 'El empleador debe identificar y registrar las sustancias químicas cancerígenas y aplicar el Sistema Globalmente Armonizado (SGA)...',
    weight: 3.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar inventario de químicos con Fichas de Datos de Seguridad (FDS de 16 secciones) etiquetadas bajo SGA.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-4.1.4',
    code: '4.1.4',
    cycle: 'HACER',
    numeralGroup: '4.1 Identificación de Peligros y Valoración de Riesgos',
    title: 'Mediciones Ambientales Periódicas de Agentes Físicos y Químicos',
    criterion: 'Realizar mediciones higiénicas cuantitativas de agentes físicos (ruido, iluminación, vibración) y químicos según los riesgos identificados.',
    decreto1072Article: 'Art. 2.2.4.6.24',
    decreto1072Title: 'Monitoreo ambiental y mediciones higiénicas',
    decreto1072Excerpt: 'Realizar mediciones cuantitativas ambientales que permitan verificar si se superan los Valores Límites Permisibles (TLV)...',
    weight: 4.0,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar informes de sonometría, dosimetría o luxometría ejecutados por laboratorio con calibración vigente.',
    status: 'CUMPLE',
    evidenceIds: ['b-sst-05'],
    actionType: 'GENERAL'
  },
  {
    id: 'std-4.2.1',
    code: '4.2.1',
    cycle: 'HACER',
    numeralGroup: '4.2 Medidas de Prevención y Control',
    title: 'Aplicación de Medidas de Prevención y Control con Jerarquía (Eliminación a EPP)',
    criterion: 'Implementar medidas de prevención y control jerarquizadas: Eliminación, Sustitución, Controles de Ingeniería, Administrativos y EPP.',
    decreto1072Article: 'Art. 2.2.4.6.24',
    decreto1072Title: 'Medidas de prevención y control jerarquizadas',
    decreto1072Excerpt: 'Las medidas de prevención y control deben adoptarse con base en el siguiente orden de prioridad: 1. Eliminación; 2. Sustitución; 3. Controles de Ingeniería; 4. Controles Administrativos; 5. Equipos y Elementos de Protección Personal...',
    weight: 2.5,
    applicableIn7: true,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Constatar la coherencia entre los controles propuestos en la Matriz GTC 45 y los controles físicamente instalados en planta.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'HAZARDS'
  },
  {
    id: 'std-4.2.2',
    code: '4.2.2',
    cycle: 'HACER',
    numeralGroup: '4.2 Medidas de Prevención y Control',
    title: 'Verificación de Aplicación de Medidas de Prevención por Trabajadores',
    criterion: 'Verificar en campo que los trabajadores conozcan y apliquen efectivamente las medidas de prevención y control de riesgos.',
    decreto1072Article: 'Art. 2.2.4.6.10',
    decreto1072Title: 'Responsabilidades de los trabajadores',
    decreto1072Excerpt: 'Los trabajadores deben procurar el cuidado integral de su salud, suministrar información clara y cumplir las normas de SST...',
    weight: 2.5,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar observaciones de comportamiento en puesto de trabajo y listas de chequeo operacional.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'INSPECTION'
  },
  {
    id: 'std-4.2.3',
    code: '4.2.3',
    cycle: 'HACER',
    numeralGroup: '4.2 Medidas de Prevención y Control',
    title: 'Procedimientos, Instructivos y Fichas de Seguridad en Puestos Críticos',
    criterion: 'Elaborar procedimientos de trabajo seguro, permisos de trabajo de alto riesgo (alturas, caliente, confinados) y fichas de seguridad.',
    decreto1072Article: 'Art. 2.2.4.6.24',
    decreto1072Title: 'Estandarización de procesos y permisos de trabajo seguro',
    decreto1072Excerpt: 'Establecer procedimientos, instructivos, fichas técnicas y permisos de trabajo que garanticen la realización segura de tareas críticas...',
    weight: 2.5,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar permisos de trabajo en alturas/espacios confinados debidamente diligenciados con listas de verificación previas.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-4.2.4',
    code: '4.2.4',
    cycle: 'HACER',
    numeralGroup: '4.2 Medidas de Prevención y Control',
    title: 'Inspecciones Periódicas a Instalaciones, Maquinaria, Herramientas y Equipos',
    criterion: 'Realizar inspecciones periódicas de seguridad con participación del COPASST a equipos de emergencia, orden y aseo y máquinas.',
    decreto1072Article: 'Art. 2.2.4.6.24 Numeral 5',
    decreto1072Title: 'Inspecciones periódicas de seguridad',
    decreto1072Excerpt: 'Realizar inspecciones periódicas a las instalaciones, maquinaria y equipos, incluidos los de emergencia, con la participación del Comité Paritario...',
    weight: 2.5,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Verificar cronograma y actas de inspección en campo a extintores, botiquines, maquinaria y montacargas.',
    status: 'CUMPLE',
    evidenceIds: ['asset-ext-01', 'asset-veh-01', 'asset-kit-01'],
    actionType: 'INSPECTION'
  },
  {
    id: 'std-4.2.5',
    code: '4.2.5',
    cycle: 'HACER',
    numeralGroup: '4.2 Medidas de Prevención y Control',
    title: 'Mantenimiento Periódico Correctivo y Preventivo de Instalaciones y Equipos',
    criterion: 'Ejecutar el programa de mantenimiento preventivo y correctivo de instalaciones locativas, maquinaria, herramientas y vehículos.',
    decreto1072Article: 'Art. 2.2.4.6.24 Numeral 6',
    decreto1072Title: 'Mantenimiento preventivo y correctivo',
    decreto1072Excerpt: 'Implementar un programa de mantenimiento periódico preventivo y correctivo de las instalaciones, equipos, máquinas y herramientas...',
    weight: 2.5,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar hojas de vida de máquinas, fichas técnicas y órdenes de trabajo ejecutadas por personal calificado.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'INSPECTION'
  },
  {
    id: 'std-4.2.6',
    code: '4.2.6',
    cycle: 'HACER',
    numeralGroup: '4.2 Medidas de Prevención y Control',
    title: 'Entrega de Elementos de Protección Personal (EPP) y Reposición con Registro',
    criterion: 'Suministrar EPP con certificación de calidad conforme a los peligros, capacitar en su uso y mantener registros de entrega firmados.',
    decreto1072Article: 'Art. 2.2.4.6.24 Numeral 5',
    decreto1072Title: 'Suministro y reposición de EPP',
    decreto1072Excerpt: 'Suministrar los equipos y elementos de protección personal (EPP) acordes a los peligros, capacitar en su uso adecuado y reponerlos...',
    weight: 2.5,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar fichas técnicas de los EPP suministrados y planillas de entrega con firmas y fechas actualizadas.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },

  // 5. GESTIÓN DE AMENAZAS (10.0%)
  {
    id: 'std-5.1.1',
    code: '5.1.1',
    cycle: 'HACER',
    numeralGroup: '5.1 Prevención, Preparación y Respuesta ante Emergencias',
    title: 'Plan de Prevención, Preparación y Respuesta ante Emergencias',
    criterion: 'Formular e implementar el Plan de Emergencias con análisis de vulnerabilidad, planos de evacuación, recursos y procedimientos PON.',
    decreto1072Article: 'Art. 2.2.4.6.25',
    decreto1072Title: 'Prevención, preparación y respuesta ante emergencias',
    decreto1072Excerpt: 'El empleador o contratante debe implementar y mantener las disposiciones necesarias en materia de prevención, preparación y respuesta ante emergencias, con cobertura a todas las sedes y turnos...',
    weight: 5.0,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar documento del Plan de Emergencias con análisis de vulnerabilidad por amenaza y planos de evacuación visibles en sedes.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'EMERGENCY'
  },
  {
    id: 'std-5.1.2',
    code: '5.1.2',
    cycle: 'HACER',
    numeralGroup: '5.1 Prevención, Preparación y Respuesta ante Emergencias',
    title: 'Brigada de Emergencias Conformada, Capacitada y Dotada',
    criterion: 'Conformar, dotar y capacitar a la brigada de emergencias (primeros auxilios, contraincendios y evacuación) con cobertura en todos los turnos.',
    decreto1072Article: 'Art. 2.2.4.6.25 Numeral 11',
    decreto1072Title: 'Conformación y dotación de la brigada de emergencia',
    decreto1072Excerpt: 'Conformar, capacitar, entrenar y dotar la brigada de emergencias, acorde a su nivel de riesgo y los recursos disponibles...',
    weight: 2.5,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Revisar acta de conformación de la brigada, dotación (chalecos, silbatos, botiquín) y certificados de entrenamiento.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'EMERGENCY'
  },
  {
    id: 'std-5.1.3',
    code: '5.1.3',
    cycle: 'HACER',
    numeralGroup: '5.1 Prevención, Preparación y Respuesta ante Emergencias',
    title: 'Realización de Simulacros de Evacuación y Emergencia Anuales',
    criterion: 'Realizar al menos un simulacro de emergencia al año con participación de todos los trabajadores y evaluar sus resultados.',
    decreto1072Article: 'Art. 2.2.4.6.25 Parágrafo 2',
    decreto1072Title: 'Simulacros periódicos de emergencia',
    decreto1072Excerpt: 'Realizar simulacros como mínimo una (1) vez al año con la participación de todos los trabajadores...',
    weight: 2.5,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar guion del simulacro, registro fotográfico y acta de evaluación con tiempos de respuesta y plan de mejora.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'EMERGENCY'
  },

  // ==========================================
  // III. CICLO VERIFICAR (5.0%)
  // 6. VERIFICACIÓN DEL SG-SST (5.0%)
  // ==========================================
  {
    id: 'std-6.1.1',
    code: '6.1.1',
    cycle: 'VERIFICAR',
    numeralGroup: '6.1 Verificación del Sistema de Gestión de SST',
    title: 'Definición y Medición de Indicadores de Estructura del SG-SST',
    criterion: 'Definir y medir los indicadores de estructura que evalúan la disponibilidad de recursos, política, plan de trabajo y responsabilidades.',
    decreto1072Article: 'Art. 2.2.4.6.20',
    decreto1072Title: 'Indicadores que evalúan la estructura del SG-SST',
    decreto1072Excerpt: 'Para la definición y construcción de los indicadores que evalúan la estructura, el empleador debe considerar entre otros: la política, objetivos, plan de trabajo, asignación de responsabilidades y recursos...',
    weight: 1.25,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar matriz de indicadores con fichas técnicas de los indicadores de estructura y su cumplimiento.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-6.1.2',
    code: '6.1.2',
    cycle: 'VERIFICAR',
    numeralGroup: '6.1 Verificación del Sistema de Gestión de SST',
    title: 'Definición y Medición de Indicadores de Proceso del SG-SST',
    criterion: 'Definir y evaluar los indicadores de proceso: ejecución del plan anual, cobertura de capacitación, ejecución del presupuesto e intervenciones.',
    decreto1072Article: 'Art. 2.2.4.6.21',
    decreto1072Title: 'Indicadores que evalúan el proceso del SG-SST',
    decreto1072Excerpt: 'Para los indicadores que evalúan el proceso, se debe considerar: evaluación inicial, ejecución del plan de trabajo, ejecución del presupuesto, ejecución del programa de capacitación...',
    weight: 1.25,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar gráficas y reportes trimestrales de cumplimiento del plan anual y capacitaciones.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-6.1.3',
    code: '6.1.3',
    cycle: 'VERIFICAR',
    numeralGroup: '6.1 Verificación del Sistema de Gestión de SST',
    title: 'Definición y Medición de Indicadores de Resultado del SG-SST',
    criterion: 'Medir los indicadores de resultado: cumplimiento de objetivos, análisis de la accidentalidad y enfermedad laboral, y evaluación de no conformidades.',
    decreto1072Article: 'Art. 2.2.4.6.22',
    decreto1072Title: 'Indicadores que evalúan el resultado del SG-SST',
    decreto1072Excerpt: 'Los indicadores que evalúan el resultado deben considerar: cumplimiento de los objetivos en SST, evaluación de las acciones preventivas y correctivas, análisis del ausentismo y accidentalidad...',
    weight: 1.25,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar reporte consolidado de indicadores de resultado del periodo fiscal.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-6.1.4',
    code: '6.1.4',
    cycle: 'VERIFICAR',
    numeralGroup: '6.1 Verificación del Sistema de Gestión de SST',
    title: 'Auditoría Interna Anual Planificada y Concertada con el COPASST',
    criterion: 'Planificar y realizar como mínimo una auditoría interna de cumplimiento anual del SG-SST con participación del COPASST.',
    decreto1072Article: 'Art. 2.2.4.6.29 y Art. 2.2.4.6.30',
    decreto1072Title: 'Auditoría de cumplimiento del SG-SST y alcance de la auditoría',
    decreto1072Excerpt: 'El empleador debe realizar una auditoría anual, la cual será planificada con la participación del Comité Paritario o Vigía de Seguridad y Salud en el Trabajo...',
    weight: 0.625,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Solicitar informe final de auditoría interna firmado por auditor calificado y acta de socialización al COPASST.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },
  {
    id: 'std-6.1.5',
    code: '6.1.5',
    cycle: 'VERIFICAR',
    numeralGroup: '6.1 Verificación del Sistema de Gestión de SST',
    title: 'Revisión por la Alta Dirección Anual Documentada en Actas',
    criterion: 'La alta dirección debe revisar el SG-SST como mínimo una vez al año para determinar su conveniencia, adecuación y eficacia.',
    decreto1072Article: 'Art. 2.2.4.6.31',
    decreto1072Title: 'Revisión por la alta dirección',
    decreto1072Excerpt: 'La alta dirección, independiente del tamaño de la empresa, debe adelantar una revisión del Sistema de Gestión de la Seguridad y Salud en el Trabajo (SG-SST), la cual debe realizarse por lo menos una (1) vez al año...',
    weight: 0.625,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar acta formal de revisión por la dirección suscrita por el Gerente General y los líderes del sistema.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'GENERAL'
  },

  // ==========================================
  // IV. CICLO ACTUAR (10.0%)
  // 7. MEJORAMIENTO (10.0%)
  // ==========================================
  {
    id: 'std-7.1.1',
    code: '7.1.1',
    cycle: 'ACTUAR',
    numeralGroup: '7.1 Acciones Preventivas y Correctivas',
    title: 'Definición de Acciones Preventivas y Correctivas (ACPM) Basadas en Auditorías e Investigaciones',
    criterion: 'Definir e implementar acciones preventivas y correctivas basadas en resultados de auditorías, inspecciones, no conformidades e investigaciones de AT.',
    decreto1072Article: 'Art. 2.2.4.6.33',
    decreto1072Title: 'Acciones preventivas y correctivas',
    decreto1072Excerpt: 'El empleador debe garantizar que se definan e implementen las acciones preventivas y correctivas necesarias, con base en los resultados de la supervisión, auditorías y de las revisiones por la alta dirección...',
    weight: 2.5,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Verificar la Matriz ACPM con planes de acción que incluyan responsable, fecha de ejecución y análisis de causa raíz.',
    status: 'CUMPLE',
    evidenceIds: ['ACPM-001'],
    actionType: 'ACPM'
  },
  {
    id: 'std-7.1.2',
    code: '7.1.2',
    cycle: 'ACTUAR',
    numeralGroup: '7.1 Acciones Preventivas y Correctivas',
    title: 'Acciones de Mejora Continua Formuladas a Partir de Recomendaciones ARL y Autoridades',
    criterion: 'Implementar las medidas y recomendaciones emitidas por la ARL y autoridades gubernamentales competentes.',
    decreto1072Article: 'Art. 2.2.4.6.34',
    decreto1072Title: 'Mejora continua',
    decreto1072Excerpt: 'El empleador debe dar las directrices y otorgar los recursos necesarios para la mejora continua del SG-SST, adoptando las recomendaciones de la ARL y del Ministerio del Trabajo...',
    weight: 2.5,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar informes de asesoría técnica de la ARL con evidencias de cierre de las recomendaciones dadas.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'ACPM'
  },
  {
    id: 'std-7.1.3',
    code: '7.1.3',
    cycle: 'ACTUAR',
    numeralGroup: '7.1 Acciones Preventivas y Correctivas',
    title: 'Plan de Mejoramiento Institucional Formulado según Autoevaluación Anual',
    criterion: 'Formular y radicar el Plan de Mejoramiento del SG-SST ante el Ministerio de Trabajo y la ARL conforme a la autoevaluación de estándares.',
    decreto1072Article: 'Art. 2.2.4.6.34 y Res. 0312 Art. 27 y 28',
    decreto1072Title: 'Plan de mejoramiento institucional',
    decreto1072Excerpt: 'Toda empresa debe formular el plan de mejoramiento derivado de la autoevaluación de Estándares Mínimos y remitirlo anualmente a la ARL para su respectivo seguimiento...',
    weight: 2.5,
    applicableIn7: false,
    applicableIn21: true,
    applicableIn60: true,
    modeOfVerification: 'Solicitar reporte de autoevaluación de Estándares Mínimos radicado en el fondo de riesgos laborales y plan de mejora concertado.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'ACPM'
  },
  {
    id: 'std-7.1.4',
    code: '7.1.4',
    cycle: 'ACTUAR',
    numeralGroup: '7.1 Acciones Preventivas y Correctivas',
    title: 'Ejecución del Plan de Mejora y Verificación de Eficacia de Acciones',
    criterion: 'Evaluar periódicamente la eficacia de las acciones correctivas, preventivas y de mejora implementadas en el SG-SST.',
    decreto1072Article: 'Art. 2.2.4.6.34 Parágrafo 1',
    decreto1072Title: 'Verificación de la eficacia de las acciones',
    decreto1072Excerpt: 'Verificar sistemáticamente que las acciones correctivas y preventivas adoptadas no vuelvan a permitir la ocurrencia de la no conformidad o desviación...',
    weight: 2.5,
    applicableIn7: false,
    applicableIn21: false,
    applicableIn60: true,
    modeOfVerification: 'Revisar auditorías de seguimiento a la Matriz ACPM con dictámenes formales de eficacia aprobados.',
    status: 'CUMPLE',
    evidenceIds: [],
    actionType: 'ACPM'
  }
];

// Helper functions for dynamic standard calculations and filtering
export function getRequiredStandardsCount(employeeCount: number, riskLevelArl: number): 7 | 21 | 60 {
  if (employeeCount <= 10 && riskLevelArl <= 3) return 7;
  if (employeeCount <= 50 && riskLevelArl <= 3) return 21;
  return 60;
}

export function isStandardApplicable(standard: SstStandardDefinition, requiredCount: 7 | 21 | 60): boolean {
  if (requiredCount === 7) return standard.applicableIn7;
  if (requiredCount === 21) return standard.applicableIn21;
  return standard.applicableIn60;
}

export function calculateScore(standards: SstStandardDefinition[], requiredCount: 7 | 21 | 60) {
  const applicable = standards.filter(s => isStandardApplicable(s, requiredCount));
  const totalWeight = applicable.reduce((acc, curr) => acc + curr.weight, 0);

  const earnedWeight = applicable.reduce((acc, curr) => {
    if (curr.status === 'CUMPLE' || curr.status === 'NO_APLICA_JUSTIFICADO') {
      return acc + curr.weight;
    }
    if (curr.status === 'EN_PROCESO') {
      return acc + (curr.weight * 0.5);
    }
    return acc;
  }, 0);

  const percentage = totalWeight > 0 ? (earnedWeight / totalWeight) * 100 : 0;

  let level: 'CRITICO' | 'MODERADAMENTE_ACEPTABLE' | 'ACEPTABLE' = 'CRITICO';
  let badgeColor = 'rose';
  let legalConsequence = 'Valoración menor al 60%: Plan de Mejoramiento inmediato y envío a la ARL / MinTrabajo.';

  if (percentage >= 85) {
    level = 'ACEPTABLE';
    badgeColor = 'emerald';
    legalConsequence = 'Mayor al 85%: Mantener la calificación y ejecutar plan anual con auditoría.';
  } else if (percentage >= 60) {
    level = 'MODERADAMENTE_ACEPTABLE';
    badgeColor = 'amber';
    legalConsequence = 'Entre 60% y 85%: Formular plan de mejora a disposición del MinTrabajo.';
  }

  return {
    applicableCount: applicable.length,
    totalStandardsInCatalog: standards.length,
    totalWeight: Number(totalWeight.toFixed(2)),
    earnedWeight: Number(earnedWeight.toFixed(2)),
    percentage: Number(percentage.toFixed(1)),
    level,
    badgeColor,
    legalConsequence
  };
}
